### ISSUE TITLE
TypeScript defintions/docs lacking

### ISSUE THREAD

**Issue by nickyvanurk** [MozillaReality/ecsy#173]
Hi there,

I only now just realized I can type "world.entityManager" because in TypeScript it didn't show up as a possiblity, same goes for creating a named entity "world.createEntity('name')". It's pretty problematic when you are learning ecsy. I also didn't know I could create a named entity because it's not in the docs.

**Comment by fernandojsg** [comment]
@nickyvanurk sorry for that :) We haven't documented some of the features yet as we are working on refactoring and adding some new features to the core so we were just waiting for these changes instead of documenting something that could be modified with them.
Regarding the typescript definitions you are right, we also have that on the to-do list but hopefully it will get better as soon as we finish this work.

**Comment by fernandojsg** [comment]
Closing this one in favor of a centralized issue with all the things that need documentation / update on the type definitions https://github.com/MozillaReality/ecsy/issues/165
