### ISSUE TITLE
Add method Entity.addComponents()

### ISSUE THREAD

**Issue by sync3ds** [MozillaReality/ecsy#183]
It would be helpful to add this method, calling it with an array of components, instead of multiple calls to addComponent().

Something like:
`entity.addComponents( [ ComponentA, ComponentB, ComponentC ] );`

**Comment by KuroTsuto** [comment]
If this were to be implemented, I think it would make sense semantically as well as with regards to QOL to take individual components as arguments rather than an array of components.

To preserve `values` functionality, it should probably also accept 2-element arrays consisting of component class and `values` data. This would allow you to do something like
```js
entity.addComponents(
  Position,
  [Rotation,{
    x: 0,
    y: 1
  }],
  [Texture,{
    image: 'path/to/spaceship.png'
  }]
)
```
Similarly, it would be convenient if `app.createEntity()` would accept initial components as well.

I don't feel it's too much effort to implement this on top of the framework as it stands, however.

**Comment by fernandojsg** [comment]
Yeah I feel it won't introduce much value as @bosconian-dynamics mentioned we should need to provide a way to set the values, and also in that way you are also creating arrays and objects just to pass the params which is not nice for GC. 
So it's not just adding syntactic sugar but also introducing a potential bad practise for uses, so I'd prefer to skip that.
