### ISSUE TITLE
type ComponentProps should not union with false

### ISSUE THREAD

**Issue by wingyplus** [MozillaReality/ecsy#199]
**Problems:**

Consider example below:

```typescript
export interface MatterSpriteProps {
  sprite: Phaser.Physics.Matter.Sprite
}

export class MatterSprite extends Component<MatterSpriteProps> {
  public sprite?: Phaser.Physics.Matter.Sprite

  constructor(props?: ComponentProps<MatterSpriteProps>) {
    super(props)
    if (typeof (props) === "boolean") {
      throw new Error("expected `props?` to be `MatterSpriteProps`, got `false`")
    }
    this.sprite = props?.sprite
  }

  public copy(source: this): this {
    this.sprite = source.sprite
    return this
  }
}
```

Inside `MatterSprite` constructure we needs to handle `props` in boolean case because `ComponentProps<P>` in https://github.com/MozillaReality/ecsy/blob/dev/src/Component.d.ts#L7 declared it as `P | false`. I didn't see any place construct component by passing a boolean `false` to the component (except undefined which come from `ObjectPool`).

**Solution:** 

Change `type ComponentProps<P>` to be `P` (not `P | false`) if there's no place to send `false`  value.

**Comment by robertlong** [comment]
We handle passing `false` to the constructor here https://github.com/MozillaReality/ecsy/blob/dev/src/Component.js#L3

Passing false disables the default constructor implementation introduced by schemas. So instead of making `ComponentProps` a union type, we'll need to do it in the constructor definition here: https://github.com/MozillaReality/ecsy/blob/dev/src/Component.js#L3

**Comment by wingyplus** [comment]
Thanks for your clarify.

**Comment by robertlong** [comment]
No problem 👍
